//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TechDatabaseEntities : DbContext
    {
        public TechDatabaseEntities()
            : base("name=TechDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ControlPoint> ControlPoint { get; set; }
        public virtual DbSet<Journal> Journal { get; set; }
        public virtual DbSet<TechnicalObjects> TechnicalObjects { get; set; }
    }
}
